// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DbFirstApproachPowerTools.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DbFirstApproachPowerTools.Models
{
    public partial class NORTHWNDContext
    {
        private INORTHWNDContextProcedures _procedures;

        public virtual INORTHWNDContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new NORTHWNDContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public INORTHWNDContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class NORTHWNDContextProcedures : INORTHWNDContextProcedures
    {
        private readonly NORTHWNDContext _context;

        public NORTHWNDContextProcedures(NORTHWNDContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetCustomerOrderHistoryResult>> GetCustomerOrderHistoryAsync(string customerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CustomerID",
                    Size = 10,
                    Value = customerID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetCustomerOrderHistoryResult>("EXEC @returnValue = [dbo].[GetCustomerOrderHistory] @CustomerID = @CustomerID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
