// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using DbFirstApproachPowerTools.Models;

namespace DbFirstApproachPowerTools.Models
{
    public partial class NORTHWNDContext
    {

        [DbFunction("CalculateOrderValue", "dbo")]
        public static decimal? CalculateOrderValue(int? OrderId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
